name: JacksaFactions
author: benjaminbecker7
main: com.bmbecker.plugin.JacksaFactions
version: 1.1.6
api-version: 1.16
depend: [WorldGuard]
commands:
  faction:
    description: base command for factions
    usage: /<command>