name: JacksaFactions
author: benjaminbecker7
main: com.bmbecker.plugin.JacksaFactions
version: 2.0.1
api-version: 1.16
depend: [WorldGuard, MySQL]
commands:
  faction:
    description: base command for factions
    usage: /<command>